

FLASK_DEBUG = True  # False debug mode in production

FLASK_SERVER_NAME = '0.0.0.0'
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = True
RESTPLUS_ERROR_404_HELP = False

# excel file path
EXCEL_DATA_EGRID_URI = 'data/egrid2016_data.xlsx'
EXCEL_DATA_COL_INDEX_NAME = 'ORISPL'
EXCEL_DATA_SHEET_NAME = 'PLNT16'


# csv file
CSV_IMG_DATA ='data/img.csv'
