app:
  build: .
  command: python3 rest_api_demo/app.py
  container_name: flaskapp
  ports:
    - "5000:5000"
  volumes:
    - .:/rest_api_demo
  links:
    - db
db:
  image: mongo:latest
  hostname: img_mongodb
  environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  ports:
    - 27017:27017
