version: '3.4'
services:
  web:
    container_name: nginx
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - "80:80"
    command: nginx -g "daemon off";
    depends_on:
      - python_api
      - db
  db:
    image: mongo:latest
    hostname: img_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017

  python_api:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    command: gunicorn -w 1 app:app -b :5000 --reload
    links:
      - db

